name: Unity Game-CI Test Automation

on:
  push:
    branches:
      - main

jobs:
  unity-test-job:
    runs-on: [self-hosted, linux, 22]
    steps:
      # - name: Fix workspace permissions
      #   run: |
      #     echo "Cleaning up messed up permissions..."
      #     sudo chown -R $(whoami):$(id -gn) ${GITHUB_WORKSPACE} || true

      # - name: Clean up problematic Game-CI paths
      #   run: |
      #     echo "Cleaning up BlankProject and game-ci artifacts..."
      #     sudo rm -rf ${{ github.workspace }}/../_actions/game-ci

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
          repository: 'blogharu/unity-test-private' # 가져올 저장소 경로
          path: 'Packages'

      - name: Delete Package Test
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'Packages/optitrack.perception/Tests';
            
            if (fs.existsSync(path)) {
              fs.rmSync(path, { recursive: true, force: true });
              console.log(`Successfully deleted ${path}`);
            } else {
              console.log(`${path} does not exist.`);
            }

      - name: Set new Package path
        uses: jackson20/string-replace-action@v1
        with:
          files: './Packages/manifest.json' 
          find: '"my.package": "file:C:/my.package"'
          replace: '"my.package": "file:my.package"'

      - name: Run Unity EditMode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode

      # - name: Post Run Fix Permissions
      #   if: always()
      #   run: sudo chown -R $USER:$USER .