name: Unity Game-CI Test Automation

on:
  push:
    branches:
      - main

jobs:
  unity-test-job:
    runs-on: [self-hosted, linux, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
          repository: 'blogharu/unity-test-private'
          path: 'PackagesRepo'

      - name: Delete Package Test
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'PackagesRepo/optitrack.perception/Tests';
            
            if (fs.existsSync(path)) {
              fs.rmSync(path, { recursive: true, force: true });
              console.log(`Successfully deleted ${path}`);
            } else {
              console.log(`${path} does not exist.`);
            }

            let filePath = 'Packages/manifest.json';

            let content = fs.readFileSync(filePath, 'utf8');

            content = content.replace('    "optitrack.perception": "file:/home/blogharu/Desktop/OptiTrack-Data-Generation-Unity-dev/unity-test-private/optitrack.perception",', '    "optitrack.perception": "file:../PackagesRepo/optitrack.perception",');

            fs.writeFileSync(filePath, content, 'utf8');
            
      - name: Run Unity EditMode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
          runAsHostUser: true
